services:
  db:
    image: postgres:latest
    container_name: fittrack-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./database/migrations:/docker-entrypoint-initdb.d

volumes:
  pgdata: