services:
  db:
    image: postgres:16
    container_name: fittrack-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql
      - ./database/migrations:/docker-entrypoint-initdb.d

  api:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: fittrack-api
    environment:
      - ASPNET_URLS=http://+:8080
      - ConnectionStrings__PGConnectionString=Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - JwtSettings__Key=${JWT_KEY}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - JwtSettings__ExpiryMinutes=${JWT_EXPIRY}
    depends_on:
      - db

  web:
    build:
      context: ./src/frontend-react
      dockerfile: Dockerfile
    container_name: fittrack-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - api

volumes:
  pgdata:
