server {
    listen 80;
    server_name fitcadence.net www.fitcadence.net;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name fitcadence.net www.fitcadence.net;

    ssl_certificate /etc/letsencrypt/live/fitcadence.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fitcadence.net/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://api:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}